# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rpi-fastboot"
BBFILE_PATTERN_meta-rpi-fastboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rpi-fastboot = "6"

LAYERDEPENDS_meta-rpi-fastboot = "core"
LAYERSERIES_COMPAT_meta-rpi-fastboot = "scarthgap"

# Configure BusyBox to act as the primary manager for runtime environments
VIRTUAL-RUNTIME_init_manager = "busybox"
VIRTUAL-RUNTIME_login_manager = "busybox"
VIRTUAL-RUNTIME_dev_manager = "busybox"
